### ISSUE TITLE
希望能够推出符合使用习惯的.rd功能

### ISSUE THREAD

**Issue by beserah** [dynilath/coolq-dicebot#20]
求推一个可以设置默认面数的rd功能orz

**Comment by beserah** [comment]
哦对还有能不能把rs功能做一个可设置是否开关的QωQ

**Comment by dynilath** [comment]
(๑•̀ㅂ•́)و✧ 
我可以很快上个.rs-on和.rs-off的玩意儿。
默认骰要等一段时间，我会和记录表单功能一起做完。

**Comment by beserah** [comment]
d(ŐдŐ๑)哇哦！希望可以先发布默认骰，毕竟至少coc这边大家都是更习惯.rd

**Comment by dynilath** [comment]
等等，coc不是有.c吗（

**Comment by beserah** [comment]
可是还是会比较习惯.rd啊（

**Comment by dynilath** [comment]
emmm，计划中的默认骰其实也不是.rd（
实际上是对于下面这种情况：
``` . r [描述]```
由于侦测不到任何的骰子指令，机器人会使用用户预设的一个指令代替进去，变成这样：  
``` . r [自动填充的骰子指令] [描述]```  
这样子你可以预设任何.r能骰的东西，并且也可以少打个d。  
具体使用起来感觉应该是这样：  
> dynilath：```.r攻击```  
> DiceBot：``` * dynilath 攻击 掷骰: 2d20k1 + 4 = 10```

**Comment by beserah** [comment]
我觉得最好还是有一下rd，因为还是比较多人习惯这么骰23333

**Comment by niunuinui** [comment]
(๑•̀ㅂ•́)و✧d(ŐдŐ๑)QωQ

什么是”设置默认面数的rd功能orz“

想要输入什么命令，达到什么效果？

**Comment by beserah** [comment]
就是，举个例子，.rd投出一个默认设置面数的骰子，举个例子设置为d20就.rd是骰d20，设置为d100就是.rd骰d100，算是蛮先入为主的一个使用习惯，没得骰.rd总觉得浑身难受(>﹏<)

**Comment by niunuinui** [comment]
那其实就是该输入.rd100的时候想偷懒只输入.rd啊

主要是QQ没有向上箭头的锅。
可以通过设定当没有给d的参数时候就用上一次的骰子大小来实现吧。

**Comment by niunuinui** [comment]
问了大佬说以后会有投出预先设置的默认面数骰子的功能，命令是 ```.r```
目前还没有，可能下个版本吧

**Comment by beserah** [comment]
.r其实也没差了23333

**Comment by dynilath** [comment]
emmmm，刚才说的就是.r(

**Comment by beserah** [comment]
就，大概.r做完加一个.rd时不会显示xxx投掷d？

**Comment by dynilath** [comment]
(你还是非要.rd嘛

**Comment by beserah** [comment]
毕竟是长期使用习惯23333
