### ISSUE TITLE
白药委托的新功能

### ISSUE THREAD

**Issue by bearFish-x** [dynilath/coolq-dicebot#23]
希望追加的功能：

增加一个包含发牌，洗牌的扑克牌堆，分为【发牌】和【弃牌】两个牌堆

基础四个花色的扑克牌52张，joker鬼牌的数量设定成可变【Y】

起初【发牌】牌堆的扑克牌数量为【52+y】，【弃牌】牌堆的扑克牌数量为【0】

每个用户可以通过特定指令随机从【发牌】牌堆里抽取数量为【x】的扑克牌

被抽取出来的扑克牌被归入【弃牌】牌堆

以下指令
发牌指令：每个用户可以通过特定指令随机从【发牌】牌堆里抽取数量为【x】的扑克牌，抽到的牌进行结果展示之后，直接进入弃牌堆。

洗牌指令：可把当下的【发牌】和【弃牌】两个牌堆的扑克牌合并，并重新进行洗牌，回归到初始的状态

查看指令：查看弃牌堆内的牌

**Comment by dynilath** [comment]
能写一下具体是哪个规则或者这个机制的名字吗？
我是说我至少需要一个这种规则的名称作为指令名
