### ISSUE TITLE
高级算式还有#标记和多次骰没有办法生效

### ISSUE THREAD

**Issue by Xisnow** [dynilath/coolq-dicebot#24]
作者你好，下载了你的1.62版本骰子，非常好用，泛用性很强。只是不知道为什么“#标记和多次骰”部分和扑克部分的功能没有办法生效，但基础的掷骰子功能没有问题。请问是BUG还是？这些功能都很有泛用性，使用价值很高，希望作者能修复。

已解决，刚刚看到作者你两个小时前更新了1.70，功能全部能用，感谢！

**Comment by Xisnow** [comment]
加QQ的机器人就可以，没有问题，自己开插件的机器人没有办法用上述功能

**Comment by dynilath** [comment]
抱歉我之前忘记发布1.7了（
