### ISSUE TITLE
插件拦截了所有消息

### ISSUE THREAD

**Issue by SinonJZH** [dynilath/coolq-dicebot#25]
这个插件会拦截所有消息，能不能改成只拦截掷骰子的消息，让其他消息能被别的插件处理。

**Comment by SinonJZH** [comment]
比如说在`e.block();`处理前加一个检测，在检测到消息以.开头才进行拦截？希望作者大大修一下:smiley:

**Comment by dynilath** [comment]
了解，这不麻烦

**Comment by SinonJZH** [comment]
非常感谢
