### ISSUE TITLE
在本地加载应用没有问题，放在tx云主机上却显示出错（-103）

### ISSUE THREAD

**Issue by SkmtJun** [dynilath/coolq-dicebot#26]
如题，使用的是tx云的windowsServer2016
个人猜测会不会是没有把运行库编译进去的原因，毕竟云主机的运行库肯定不是很全

**Comment by dynilath** [comment]
emmm，听起来很神秘，那个示例是在阿里云上运行的，用的是docker。

**Comment by dynilath** [comment]
由于[这个原因](https://github.com/cqmoe/cqcppsdk/blob/master/src/std_mode/api.cpp#L8)，该插件需要VC++ Runtime的支持来工作。如果运行机器上没有合适的vcrt，会报-103错误。
