### ISSUE TITLE
使用过程中的一些建议

### ISSUE THREAD

**Issue by Jigsaw111** [dynilath/coolq-dicebot#27]
1.扑克功能可以考虑加一个暗抽功能，用于群内狼人杀或者斗地主。（虽然我并不知道为什么群员要用骰子来玩斗地主和狼人杀）
2.能否实现像溯洄骰或者塔骰那样储存人物卡属性并调用，对于懒鬼来说很有必要。
3.dismiss自动退群功能以及黑名单功能。
4.自定义语言包功能以及超级管理员功能（即骰主）。

**Comment by dynilath** [comment]
1. 群内狼人和斗地主那还得搞个出牌，出牌就得考虑你有很多个群到底往哪儿出，出哪个，多提供些使用情况可以让我对具体需求有个更清晰的了解。
2. 之前这个需求是用set指令来做的，你可以先试一下[这个玩意儿](https://github.com/dynilath/coolq-dicebot#%E5%AE%9A%E4%B9%89%E9%AA%B0%E5%AD%90set%E6%88%96s)。我也希能有更直接更简便的实现方式，希望能够提供一些建议。
3. 我提供的那个实例你直接踢就是了，这个项目有一个目标是`做每个人都可以架一个的开放骰子插件`。这个插件基本上只做骰子，权限需求也是最低的，源码也摆在这里，尽量不对用户带来其他影响。什么`踢掉群里指定人`的事情，`被禁言把群拉黑`的事情这都不会去做。如果需要特别的管理功能可以去酷Q社区下，这种有很多。比如我配置的那个实例就另外加了个加群频率控制。
4. 这差不多是继续3了，骰主具体是要做啥，如果是要整一个自己的骰子，可以按照[该章节](https://github.com/dynilath/coolq-dicebot#%E5%AE%89%E8%A3%85)配置个骰子，它将完全属于配置者。

**Comment by Jigsaw111** [comment]
感谢作者愿意回复我这个不明确的需求建议，反正如果我面对的甲方是这样我已经大喊：“滚出去”了。
更感谢作者愿意在溯洄骰和塔骰已经占领几乎全部的骰子的时候继续写这个与众不同骰子插件。
那么下面我会针对之前建议来提出更多具体的使用情况描述和需求。
1.出牌这个确实是有些唐突了（我这就去打一顿我的沙雕群友），不必理会，反正其他的酷q插件有这个功能，十分抱歉。
2.这一条之前说的意识其实就是说像是存储属性而不是储存骰子。比如我储存一个力量为50，之后可以通过指令`.r1d力量`来实现`.r1d50`的功能，我知道运用set也可以实现.`r力量`等同于`.r1d50`的功能，但是如果我要再投掷`.r2d力量`呢？我总不能在set一个.`r2d50`吧。也就是说，这个需求的意思是把属性当做一个数字变量储存起来，然后之后可以再调用。
3.我提出自动退群这个需求的原因是：骰娘如果被人踢出群聊的次数过多，貌似就会被腾讯识别为机器人，从而冻结账号。所以我觉得需要一个自动退群的功能，至于禁言或者拉黑这些，其实却是无所谓。好吧，说到底就是我希望把这个功能集成到一个插件里，省得去找。（果然骰主都是懒鬼吗）也有考虑到某些骰主对于酷q这一软件的了解不够，让他们去寻找别的插件可能有些困难。（其实我也想说：“爱用用，不爱用就滚蛋！”）
4.骰主的功能的话，我想的就是要不要有个指令能够让骰子转述一些话给骰主，好让骰主了解这个骰子有没有出现什么情况或者对骰主有什么建议，或者可以让骰主命令骰子清退一些不活跃的群聊。
哦，对了，还有一件非常重要的事情，骰子的指令能不能适配一下中文的句号......也就是`。`

**Comment by dynilath** [comment]
2. 如下指令在现在是支持的
> dynilath：`.set 50 力量`
> DiceBot：` * dynilath 设置指令: 50 为 力量`
> DiceBot：`.r1d力量`
> DiceBot：` * dynilath 掷骰: 1d50 = [44] = 44`
> DiceBot：`.r2d力量`
> DiceBot：` * dynilath 掷骰: 2d50 = [24 + 29] = 53`

3. 如你所见，我的骰子实例这么久了也没爆，问题并不在禁言和被踢上。我有时间找点比较靠谱的插件然后写在readme里好了。说到底这个项目是骰子不是综合管理附带骰子。

4. 如上，这应该是需要一个统计信息插件，我去找找。

5. 就是因为`.`本身作为开头比较少见才用。也有很多蛋疼的人喜欢发只有一个`。`的消息。另一方面现在输入法按一下shift就可以开始英文输入了。仅有的麻烦其实是ios原装输入法，那个的确是恶心，打英文引号和下划线都恶心得一批。这个设计一定程度上就是为了让用户清楚意识到自己接下来是要扔骰子。

**Comment by Jigsaw111** [comment]
那么我没有任何问题了，那么请问能在README里写上你的开发环境么..

**Comment by dynilath** [comment]
我写了个这个玩意儿，或许能帮到你（
https://github.com/dynilath/invite_controller
