### ISSUE TITLE
感谢以及一个小建议

### ISSUE THREAD

**Issue by Nilajor** [dynilath/coolq-dicebot#28]
谢谢老板的源码，感觉骰娘升级了
不过有个小建议。
关于不指定名称的.s功能
体感在跑团过程中的应用不算特别大，常用的几个可以.s + 定义名解决
能否将.s默认修改为指定默认骰面数？
这样设置后可以兼容.r d、.r d+5等常用R点方式

**Comment by dynilath** [comment]
这里默认骰并不用`d`表示，而是什么都不写来表示。
例如
> dynilath : `.s d20`
> OpenDiceBot : ` * dynilath 设置默认骰子指令: (d20)`
> dynilath : `.r`
> OpenDiceBot : `* dynilath 掷骰: (d20) = ([18]) = 18`

如果你需要设定`d`为某种特别的骰子
可以`.s 1d100 d`这样
> dynilath : `.s 1d100 d`
> OpenDiceBot : ` * dynilath 设置指令: (1d100) 为 d`
> dynilath : `.r d+4`
> OpenDiceBot : ` * dynilath 掷骰: (1d100) + 4 = ([70]) + 4 = 74`

其实这个部分有很多小问题
例如由于[定义骰子](https://github.com/dynilath/coolq-dicebot#%E5%AE%9A%E4%B9%89%E9%AA%B0%E5%AD%90set%E6%88%96s)功能中，定义的具有名字的骰子是可以用于默认骰子的。由于写得有些粗糙，会导致设置默认骰子时，解析器出一些奇怪的毛病。  
例如，若设定`.s 1d100 d`。再执行`.s 1d20`就会出毛病。
这计划在下个版本中修复。
