### ISSUE TITLE
如何将骰子移出群？

### ISSUE THREAD

**Issue by Avogad** [dynilath/coolq-dicebot#32]
骰主您好，跑团群里的骰子略多，想移除几个，但又担心把dicebot直接踢出群会导致它被屏蔽，想问一下这个骰有没有自动退群指令？或者如果您方便的话帮忙手动操作一下，本人qqID为2796844859，看到请联系，谢谢您。

**Comment by dynilath** [comment]
直接踢，不会屏蔽

**Comment by Avogad** [comment]
好的，谢谢了✓

dynilath ***@***.***>于2021年4月3日 周六下午11:47写道：
